version: "3.8"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - appnet

  web:
    image: devops_assignment_web:latest
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    depends_on:
      - db
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    ports:
      - "80:8000"
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
    driver: overlay
